/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.salmos.item.view;

import br.com.ifba.salmos.fornecedor.model.Fornecedor;
import br.com.ifba.salmos.homescreen.view.homescreen;
import br.com.ifba.salmos.infrastructure.service.FacadeInstance;
import br.com.ifba.salmos.infrastructure.support.StringUtil;
import br.com.ifba.salmos.item.model.Item;
import br.com.ifba.salmos.usuario.model.Usuario;
import java.awt.Color;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitor
 */
public class ViewItem extends javax.swing.JFrame {

    DefaultTableModel listaItem;
    List<Item> itemLista;
    List<Item> itemSelecionado;
    int selecionado;

    Item item;

    Usuario usuarioLogado;

    ComboBoxModel comboFornecedor;

    /**
     * Creates new form ViewItem
     */

    // Iniciando com o usuario logado, além de iniciar a lista de itens e
    // centralizando a tela
    public ViewItem(Usuario user) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioLogado = user;

        this.itemLista = FacadeInstance.getInstance().getAllItem();
        atualizarTabelaItem(this.itemLista);
        comboBoxAtualizarFornecedor();

        // List<Fornecedor> semfornecedor =
        // FacadeInstance.getInstance().getAllFornecedor();

    }

    public ViewItem() {
        initComponents();
        setLocationRelativeTo(null);

        this.itemLista = FacadeInstance.getInstance().getAllItem();
        atualizarTabelaItem(this.itemLista);
        comboBoxAtualizarFornecedor();
    }

    private void comboBoxAtualizarFornecedor() {
        cbbFornecedor.removeAll();
        cbbFornecedorEdit.removeAll();

        List<Fornecedor> fornecedor = FacadeInstance.getInstance().getAllFornecedor();

        for (int i = 0; i < fornecedor.size(); i++) {
            cbbFornecedor.addItem(fornecedor.get(i).getNome());
            cbbFornecedorEdit.addItem(fornecedor.get(i).getNome());
        }
    }

    // Metodo para atualizar a tabela dos itens

    private void atualizarTabelaItem(List<Item> itens) {
        this.listaItem = new DefaultTableModel(null,
                new String[] { "ID", "Nome", "Descricao", "Quantidade", "Fornecedor" });

        for (Item itm : itens) {
            listaItem.addRow(new Object[] { itm.getId(), itm.getNome(), itm.getDescricao(), itm.getQuantidade(),
                    itm.getFornecedor() });
        }

        this.tblItem.setModel(listaItem);
    }

    // Metodo para buscar o item pelo nome

    private List<Item> buscaItens(String nome) {
        if (nome == null || nome.equals("")) {
            return FacadeInstance.getInstance().getAllItem();
        }
        List<Item> search = new ArrayList<>();

        for (Item itm : this.itemLista) {
            if (itm.getNome().toLowerCase().contains(nome.toLowerCase()) ||
                    nome.toLowerCase().contains(itm.getDescricao().toLowerCase()))
                search.add(itm);
        }
        return search;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTabela = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnHomescreen = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lblDescricao1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        btnHomescreen1 = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JTextField();
        lblNome2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbFornecedor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        btnSalvarEdit = new javax.swing.JButton();
        btnExcluirEdit = new javax.swing.JButton();
        btnCancelarEdit = new javax.swing.JButton();
        txtDescricaoEdit = new javax.swing.JTextField();
        lblDescricao2 = new javax.swing.JLabel();
        txtNomeEdit = new javax.swing.JTextField();
        lblNome3 = new javax.swing.JLabel();
        lblNome4 = new javax.swing.JLabel();
        txtQuantidadeEdit = new javax.swing.JTextField();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbFornecedorEdit = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblTabela.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTabela.setText("TABELA DE ITENS");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnHomescreen.setText("Homescreen");
        btnHomescreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomescreenActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescricao.setText("Descricao");

        lblQuantidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblQuantidade.setText("Quantidade");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        lblDescricao1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao1.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao1.setText("Descrição");

        txtNome.setBackground(new java.awt.Color(253, 255, 175));
        txtNome.setBorder(null);
        txtNome.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        lblNome1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(232, 189, 72));
        lblNome1.setText("Nome");

        btnSalvar.setBackground(new java.awt.Color(232, 189, 72));
        btnSalvar.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(253, 255, 175));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(232, 189, 72));
        btnCancelar.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(253, 255, 175));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDescricao.setBackground(new java.awt.Color(253, 255, 175));
        txtDescricao.setBorder(null);
        txtDescricao.setSelectionColor(new java.awt.Color(250, 206, 86));

        btnHomescreen1.setBackground(new java.awt.Color(232, 189, 72));
        btnHomescreen1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnHomescreen1.setForeground(new java.awt.Color(253, 255, 175));
        btnHomescreen1.setText("Homescreen");
        btnHomescreen1.setBorder(null);
        btnHomescreen1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHomescreen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomescreen1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomescreen1MouseExited(evt);
            }
        });
        btnHomescreen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomescreen1ActionPerformed(evt);
            }
        });

        txtQuantidade.setBackground(new java.awt.Color(253, 255, 175));
        txtQuantidade.setBorder(null);
        txtQuantidade.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        lblNome2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(232, 189, 72));
        lblNome2.setText("Quantidade");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 189, 72));
        jLabel3.setText("Fornecedor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome2)
                                    .addComponent(txtQuantidade))
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescricao1)
                                    .addComponent(lblNome1)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnHomescreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome2)
                    .addComponent(lblNome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHomescreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Cadastro", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblItem.setRowHeight(30);
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblItem);

        btnSalvarEdit.setBackground(new java.awt.Color(232, 189, 72));
        btnSalvarEdit.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnSalvarEdit.setForeground(new java.awt.Color(253, 255, 175));
        btnSalvarEdit.setText("Salvar");
        btnSalvarEdit.setBorder(null);
        btnSalvarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarEdit.setEnabled(false);
        btnSalvarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditActionPerformed(evt);
            }
        });

        btnExcluirEdit.setBackground(new java.awt.Color(232, 189, 72));
        btnExcluirEdit.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnExcluirEdit.setForeground(new java.awt.Color(253, 255, 175));
        btnExcluirEdit.setText("Excluir");
        btnExcluirEdit.setBorder(null);
        btnExcluirEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirEdit.setEnabled(false);
        btnExcluirEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEditActionPerformed(evt);
            }
        });

        btnCancelarEdit.setBackground(new java.awt.Color(232, 189, 72));
        btnCancelarEdit.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnCancelarEdit.setForeground(new java.awt.Color(253, 255, 175));
        btnCancelarEdit.setText("Cancelar");
        btnCancelarEdit.setBorder(null);
        btnCancelarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEdit.setEnabled(false);
        btnCancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditActionPerformed(evt);
            }
        });

        txtDescricaoEdit.setBackground(new java.awt.Color(253, 255, 175));
        txtDescricaoEdit.setBorder(null);
        txtDescricaoEdit.setEnabled(false);
        txtDescricaoEdit.setSelectionColor(new java.awt.Color(250, 206, 86));

        lblDescricao2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao2.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao2.setText("Descrição");

        txtNomeEdit.setBackground(new java.awt.Color(253, 255, 175));
        txtNomeEdit.setBorder(null);
        txtNomeEdit.setEnabled(false);
        txtNomeEdit.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtNomeEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeEditKeyPressed(evt);
            }
        });

        lblNome3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblNome3.setForeground(new java.awt.Color(232, 189, 72));
        lblNome3.setText("Nome");

        lblNome4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblNome4.setForeground(new java.awt.Color(232, 189, 72));
        lblNome4.setText("Quantidade");

        txtQuantidadeEdit.setBackground(new java.awt.Color(253, 255, 175));
        txtQuantidadeEdit.setBorder(null);
        txtQuantidadeEdit.setEnabled(false);
        txtQuantidadeEdit.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtQuantidadeEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeEditKeyPressed(evt);
            }
        });

        lblBusca.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lblBusca.setText("Busque pelo nome:");

        txtBusca.setBackground(new java.awt.Color(253, 255, 175));
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 189, 72));
        jLabel5.setText("Fornecedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 33, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNome3)
                                            .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNome4)
                                            .addComponent(txtQuantidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtDescricaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel5)))
                                .addContainerGap(56, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbbFornecedorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblBusca)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNome4)
                                .addGap(18, 18, 18)
                                .addComponent(txtQuantidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNome3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblDescricao2)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescricaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbFornecedorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Editar", jPanel2);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomescreen1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomescreen1MouseEntered
        // TODO add your handling code here:
        btnHomescreen1.setContentAreaFilled(false);
        btnHomescreen1.setOpaque(true);
        btnHomescreen1.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnHomescreen1MouseEntered

    private void btnHomescreen1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomescreen1MouseExited
        // TODO add your handling code here:
        Color color = btnSalvar.getBackground();
        btnHomescreen1.setContentAreaFilled(false);
        btnHomescreen1.setOpaque(true);
        btnHomescreen1.setBackground(color);
    }//GEN-LAST:event_btnHomescreen1MouseExited

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        // TODO add your handling code here:
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(true);
        btnCancelar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        Color color = btnSalvar.getBackground();
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(true);
        btnCancelar.setBackground(color);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        // TODO add your handling code here:
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setOpaque(true);
        btnSalvar.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        // TODO add your handling code here:
        Color color = btnCancelar.getBackground();
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setOpaque(true);
        btnSalvar.setBackground(color);
    }//GEN-LAST:event_btnSalvarMouseExited

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtBuscaKeyReleased
        String nome = txtBusca.getText().toLowerCase();
        this.itemLista = buscaItens(nome);
        atualizarTabelaItem(itemLista);
    }// GEN-LAST:event_txtBuscaKeyReleased

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNomeKeyPressed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
        Item itemL = new Item();

        int quantidade = Integer.parseInt(txtQuantidade.getText());
        int i, c = cbbFornecedor.getSelectedIndex();
        List<Item> verificarItem = FacadeInstance.getInstance().getAllItem();
        List<Fornecedor> verificaFornecedor = FacadeInstance.getInstance().getAllFornecedor();

        if (validaCampos() == true) {
            itemL.setNome(txtNome.getText());
            itemL.setDescricao(txtDescricao.getText());
            itemL.setQuantidade(quantidade);
            itemL.setFornecedor(verificaFornecedor.get(c).getNome());

            for (i = 0; i < verificarItem.size(); i++) {
                if (itemL.getNome().equals(verificarItem.get(i).getNome())) {
                    JOptionPane.showMessageDialog(null, "Item já existente", "Atenção",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }

        FacadeInstance.getInstance().saveItem(itemL);

        JOptionPane.showMessageDialog(null, "Item adicionado ao estoque", "Parabens!!",
                JOptionPane.INFORMATION_MESSAGE);

        txtNome.setText("");
        txtDescricao.setText("");
        txtQuantidade.setText("");

        this.itemLista = FacadeInstance.getInstance().getAllItem();
        this.atualizarTabelaItem(itemLista);
    }// GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarActionPerformed
        txtNome.setText("");
        txtDescricao.setText("");
        txtQuantidade.setText("");
    }// GEN-LAST:event_btnCancelarActionPerformed

    private void btnHomescreen1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHomescreen1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        homescreen retornar = new homescreen(usuarioLogado);
        retornar.setVisible(true);
    }// GEN-LAST:event_btnHomescreen1ActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblItemMouseClicked
        this.selecionado = this.tblItem.getSelectedRow();

        if (this.selecionado != -1) {
            this.item = this.itemLista.get(this.selecionado);

            txtNomeEdit.setText(this.item.getNome());
            txtQuantidadeEdit.setText(String.valueOf(this.item.getQuantidade()));
            txtDescricaoEdit.setText(this.item.getDescricao());
            cbbFornecedorEdit.setSelectedItem(this.item.getFornecedor());

            txtNomeEdit.setEnabled(true);
            txtQuantidadeEdit.setEnabled(true);
            txtDescricaoEdit.setEnabled(true);

            btnCancelarEdit.setEnabled(true);
            btnSalvarEdit.setEnabled(true);
            btnExcluirEdit.setEnabled(true);
        }
    }// GEN-LAST:event_tblItemMouseClicked

    private void btnSalvarEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarEditActionPerformed

        int c = cbbFornecedorEdit.getSelectedIndex();
        List<Fornecedor> verificaFornecedor = FacadeInstance.getInstance().getAllFornecedor();

        if (this.item != null) {
            item.setNome(txtNomeEdit.getText());
            item.setDescricao(txtDescricaoEdit.getText());
            item.setQuantidade(Integer.valueOf(txtQuantidadeEdit.getText()));
            item.setFornecedor(verificaFornecedor.get(c).getNome());

            FacadeInstance.getInstance().updateItem(item);

            this.itemLista = FacadeInstance.getInstance().getAllItem();
            atualizarTabelaItem(this.itemLista);

            JOptionPane.showMessageDialog(null, "Item atualizado!", "Parabens!!",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        btnCancelarEdit.doClick();
    }// GEN-LAST:event_btnSalvarEditActionPerformed

    private void btnExcluirEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirEditActionPerformed
        FacadeInstance.getInstance().deleteItem(item);
        this.itemLista = FacadeInstance.getInstance().getAllItem();
        this.atualizarTabelaItem(itemLista);

        this.selecionado = -1;

        JOptionPane.showMessageDialog(null, "Item deletado", "Atenção", JOptionPane.WARNING_MESSAGE);
        btnCancelarEdit.doClick();
    }// GEN-LAST:event_btnExcluirEditActionPerformed

    private void btnCancelarEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelarEditActionPerformed
        txtNomeEdit.setText(null);
        txtQuantidadeEdit.setText(null);
        txtDescricaoEdit.setText(null);

        txtNomeEdit.setEnabled(false);
        txtQuantidadeEdit.setEnabled(false);
        txtDescricaoEdit.setEnabled(false);
        btnCancelarEdit.setEnabled(false);
        btnSalvarEdit.setEnabled(false);
        btnExcluirEdit.setEnabled(false);
        this.item = null;
        this.selecionado = -1;
    }// GEN-LAST:event_btnCancelarEditActionPerformed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtQuantidadeKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtNomeEditKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNomeEditKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNomeEditKeyPressed

    private void txtQuantidadeEditKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtQuantidadeEditKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtQuantidadeEditKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nome = txtBusca.getText();

        this.itemLista = buscaItens(nome);
        this.atualizarTabelaItem(itemLista);

        // txtBusca.setText("");
    }// GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        this.itemLista = FacadeInstance.getInstance().getAllItem();
        atualizarTabelaItem(this.itemLista);
    }// GEN-LAST:event_btnAtualizarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ViewEditarItem editar = new ViewEditarItem();
        editar.setVisible(true);

    }// GEN-LAST:event_btnEditarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_btnAdicionarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:

        this.itemLista = FacadeInstance.getInstance().getAllItem();
        this.atualizarTabelaItem(this.itemLista);
    }// GEN-LAST:event_btnListarActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDescricaoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_btnExcluirActionPerformed

    private void btnHomescreenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHomescreenActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        homescreen home = new homescreen();
        home.setVisible(true);
    }// GEN-LAST:event_btnHomescreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarEdit;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirEdit;
    private javax.swing.JButton btnHomescreen;
    private javax.swing.JButton btnHomescreen1;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarEdit;
    private javax.swing.JComboBox<String> cbbFornecedor;
    private javax.swing.JComboBox<String> cbbFornecedorEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTabela;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricaoEdit;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEdit;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtQuantidadeEdit;
    // End of variables declaration//GEN-END:variables
    private boolean validaCampos() {
        StringUtil util = StringUtil.getInstance();
        if (txtNome.getText().equals("") && txtDescricao.getText().equals("") && txtQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios.", "CAMPOS OBRIGATÓRIOS",
                    JOptionPane.ERROR_MESSAGE);
            return false;

        } else if (util.isNullOrEmpty(txtNome.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome.", "CAMPOS OBRIGATÓRIOS",
                    JOptionPane.WARNING_MESSAGE);
            return false;

        } else if (util.isNullOrEmpty(txtDescricao.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Descricao", "CAMPOS OBRIGATÓRIOS",
                    JOptionPane.WARNING_MESSAGE);
            return false;

        } else if (util.isNullOrEmpty(txtQuantidade.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Quantidade", "CAMPOS OBRIGATÓRIOS",
                    JOptionPane.WARNING_MESSAGE);
            return false;

        } 

        return true;
    }
}
