/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.salmos.usuario.view;

import br.com.ifba.salmos.homescreen.view.homescreen;
import br.com.ifba.salmos.infrastructure.service.FacadeInstance;
import br.com.ifba.salmos.infrastructure.support.StringUtil;
import br.com.ifba.salmos.tiposdeusuarios.model.TipoDeUsuario;
import br.com.ifba.salmos.usuario.model.Usuario;
import java.awt.Color;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class ViewUsuario extends javax.swing.JFrame {
    
    DefaultTableModel listaTabela;
    DefaultTableModel listaDescricao;
    ComboBoxModel tipoUsuario;
    List<Usuario> lista;
    List<TipoDeUsuario> listaTipo;
    List<Usuario> listaBuscar;
    int selecionado;
    boolean escolher = false;
    
    Usuario usuario;
    
    Usuario usuarioLogado;
    /**
     * Creates new form UsuarioView
     */
    
    //Iniciando com o usuario logado, além de iniciar a lista de usuarios e centralizando a tela
    public ViewUsuario(Usuario user) {
        initComponents();
        setLocationRelativeTo(null);
        CmbBoxTipoUsuario();
        
        this.usuarioLogado = user;
        
        this.lista = FacadeInstance.getInstance().getAllUsuarios();
        this.listaTipo = FacadeInstance.getInstance().getAllTipoDeUsuarios();
        this.atualizarTabela(this.lista);
        this.atualizarTabelaDescricao(this.listaTipo);
    }
    
    public ViewUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        CmbBoxTipoUsuario();
        
        this.lista = FacadeInstance.getInstance().getAllUsuarios();
        this.listaTipo = FacadeInstance.getInstance().getAllTipoDeUsuarios();
        this.atualizarTabela(this.lista);
        this.atualizarTabelaDescricao(this.listaTipo);
    }
    
    //Metodo para atualizar a tabela na view
    
    private void atualizarTabela(List<Usuario> listaUsuario){
        this.listaTabela = new DefaultTableModel(null, new String [] {"ID", "Login", "Senha", "Email", "Nome", "Tipo de Usuário"});
        
        for(Usuario usu: listaUsuario){
            listaTabela.addRow(new Object[]{usu.getId(), usu.getLogin(), usu.getSenha(), usu.getEmail(), usu.getNome(), usu.getTipodeusuario()});
        }
        
        this.tblUsuario.setModel(listaTabela);
    }
    
    //metodo para atualizar a tabela do tipo de usuario DESCRICAO
    
    private void atualizarTabelaDescricao(List<TipoDeUsuario> tipoDescricao){
        this.listaDescricao =  new DefaultTableModel(null, new String[] {"Tipo de usuário", "Descricao"});
        
        for(TipoDeUsuario tipos: tipoDescricao){
            List<TipoDeUsuario> listaTipo = FacadeInstance.getInstance().getAllTipoDeUsuarios();
            listaDescricao.addRow(new Object [] {tipos.getNome(), tipos.getDescricao()});
        }
        
        this.tblDescricao.setModel(listaDescricao);
    }
   
    //ComboBox para mostrar os tipos de usuarios
    
    private void CmbBoxTipoUsuario(){
        cbbTipoDeUsuario.removeAll();
        cbbTipoDeUsuarioEdit.removeAll();
        
        List<TipoDeUsuario> tipodeusuario = FacadeInstance.getInstance().getAllTipoDeUsuarios();
        for(int i = 0; i < tipodeusuario.size(); i++){
            cbbTipoDeUsuario.addItem(tipodeusuario.get(i).getNome());
            cbbTipoDeUsuarioEdit.addItem(tipodeusuario.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        tbpDescricao = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        lblDescricao1 = new javax.swing.JLabel();
        lblDescricao2 = new javax.swing.JLabel();
        cbbTipoDeUsuario = new javax.swing.JComboBox<>();
        lblDescricao3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnHomescreen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDescricao = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnSalvarEdit = new javax.swing.JButton();
        btnExcluirEdit = new javax.swing.JButton();
        btnCancelarEdit = new javax.swing.JButton();
        lblNome2 = new javax.swing.JLabel();
        txtEmailEdit = new javax.swing.JTextField();
        lblDescricao4 = new javax.swing.JLabel();
        txtUsuarioEdit = new javax.swing.JTextField();
        lblDescricao5 = new javax.swing.JLabel();
        txtNomeEdit = new javax.swing.JTextField();
        lblDescricao6 = new javax.swing.JLabel();
        txtSenhaEdit = new javax.swing.JPasswordField();
        lblDescricao7 = new javax.swing.JLabel();
        cbbTipoDeUsuarioEdit = new javax.swing.JComboBox<>();
        lblBuscaUsuario = new javax.swing.JLabel();
        txtBuscaUsuario = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();
        btnMostrarUsuarios = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblDescricao.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao.setText("Nome");

        txtEmail.setBackground(new java.awt.Color(253, 255, 175));
        txtEmail.setBorder(null);
        txtEmail.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        lblNome1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(232, 189, 72));
        lblNome1.setText("Email");

        btnSalvar.setBackground(new java.awt.Color(232, 189, 72));
        btnSalvar.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(253, 255, 175));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(232, 189, 72));
        btnCancelar.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(253, 255, 175));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNome.setBackground(new java.awt.Color(253, 255, 175));
        txtNome.setBorder(null);
        txtNome.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtUsuario.setBackground(new java.awt.Color(253, 255, 175));
        txtUsuario.setBorder(null);
        txtUsuario.setSelectionColor(new java.awt.Color(250, 206, 86));

        lblDescricao1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao1.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao1.setText("Usuário");

        lblDescricao2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao2.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao2.setText("Tipo do Usuário");

        cbbTipoDeUsuario.setBackground(new java.awt.Color(253, 255, 175));

        lblDescricao3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao3.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao3.setText("Senha");

        txtSenha.setBackground(new java.awt.Color(253, 255, 175));

        btnHomescreen.setBackground(new java.awt.Color(232, 189, 72));
        btnHomescreen.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnHomescreen.setForeground(new java.awt.Color(253, 255, 175));
        btnHomescreen.setText("Homescreen");
        btnHomescreen.setBorder(null);
        btnHomescreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHomescreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomescreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHomescreen, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDescricao2)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(cbbTipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(lblDescricao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(txtNome)
                                    .addGap(26, 26, 26)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescricao3)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome1)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescricao1)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDescricao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(lblDescricao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDescricao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbbTipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHomescreen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbTipoDeUsuario, txtNome});

        tbpDescricao.addTab("Cadastro", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel1.setText("Descrição do Tipo de Usuário");

        tblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblDescricao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDescricao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        tbpDescricao.addTab("Descrição", jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblUsuario.setRowHeight(30);
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUsuario);

        btnSalvarEdit.setBackground(new java.awt.Color(250, 206, 86));
        btnSalvarEdit.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnSalvarEdit.setForeground(new java.awt.Color(253, 255, 175));
        btnSalvarEdit.setText("Salvar");
        btnSalvarEdit.setBorder(null);
        btnSalvarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarEdit.setEnabled(false);
        btnSalvarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditActionPerformed(evt);
            }
        });

        btnExcluirEdit.setBackground(new java.awt.Color(250, 206, 86));
        btnExcluirEdit.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnExcluirEdit.setForeground(new java.awt.Color(253, 255, 175));
        btnExcluirEdit.setText("Excluir");
        btnExcluirEdit.setBorder(null);
        btnExcluirEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirEdit.setEnabled(false);
        btnExcluirEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEditActionPerformed(evt);
            }
        });

        btnCancelarEdit.setBackground(new java.awt.Color(250, 206, 86));
        btnCancelarEdit.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnCancelarEdit.setForeground(new java.awt.Color(253, 255, 175));
        btnCancelarEdit.setText("Cancelar");
        btnCancelarEdit.setBorder(null);
        btnCancelarEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEdit.setEnabled(false);
        btnCancelarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditActionPerformed(evt);
            }
        });

        lblNome2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(232, 189, 72));
        lblNome2.setText("Email");

        txtEmailEdit.setBackground(new java.awt.Color(253, 255, 175));
        txtEmailEdit.setBorder(null);
        txtEmailEdit.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtEmailEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailEditKeyPressed(evt);
            }
        });

        lblDescricao4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao4.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao4.setText("Usuário");

        txtUsuarioEdit.setBackground(new java.awt.Color(253, 255, 175));
        txtUsuarioEdit.setBorder(null);
        txtUsuarioEdit.setSelectionColor(new java.awt.Color(250, 206, 86));

        lblDescricao5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao5.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao5.setText("Nome");

        txtNomeEdit.setBackground(new java.awt.Color(253, 255, 175));
        txtNomeEdit.setBorder(null);
        txtNomeEdit.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtNomeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEditActionPerformed(evt);
            }
        });

        lblDescricao6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao6.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao6.setText("Senha");

        txtSenhaEdit.setBackground(new java.awt.Color(253, 255, 175));

        lblDescricao7.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        lblDescricao7.setForeground(new java.awt.Color(232, 189, 72));
        lblDescricao7.setText("Tipo do Usuário");

        cbbTipoDeUsuarioEdit.setBackground(new java.awt.Color(253, 255, 175));
        cbbTipoDeUsuarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTipoDeUsuarioEditActionPerformed(evt);
            }
        });

        lblBuscaUsuario.setBackground(new java.awt.Color(253, 255, 175));
        lblBuscaUsuario.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        lblBuscaUsuario.setText("Busque pelo nome: ");

        txtBuscaUsuario.setBackground(new java.awt.Color(253, 255, 175));

        btnBuscarUsuario.setBackground(new java.awt.Color(250, 206, 86));
        btnBuscarUsuario.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnBuscarUsuario.setForeground(new java.awt.Color(253, 255, 175));
        btnBuscarUsuario.setText("Buscar");
        btnBuscarUsuario.setBorder(null);
        btnBuscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        btnMostrarUsuarios.setBackground(new java.awt.Color(250, 206, 86));
        btnMostrarUsuarios.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        btnMostrarUsuarios.setForeground(new java.awt.Color(253, 255, 175));
        btnMostrarUsuarios.setText("Lista");
        btnMostrarUsuarios.setBorder(null);
        btnMostrarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnMostrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(lblBuscaUsuario)
                            .addGap(18, 18, 18)
                            .addComponent(txtBuscaUsuario))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDescricao7)
                        .addGap(130, 130, 130))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome2)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbTipoDeUsuarioEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSenhaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDescricao6))
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDescricao4)
                                            .addComponent(txtUsuarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnExcluirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSalvarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEmailEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescricao5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscaUsuario)
                            .addComponent(txtBuscaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSalvarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCancelarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExcluirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMostrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblNome2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescricao5)
                        .addGap(13, 13, 13)
                        .addComponent(txtNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao6)
                            .addComponent(lblDescricao4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSenhaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescricao7)
                            .addComponent(cbbTipoDeUsuarioEdit))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbTipoDeUsuarioEdit, txtNomeEdit});

        tbpDescricao.addTab("Editar", jPanel5);

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuário");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tbpDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(tbpDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Usuario usuario = new Usuario();
        
        //Chamando a lista de tipodeusuario para buscar pelo indice e verificar
        
        List<TipoDeUsuario> tipodeusuario = FacadeInstance.getInstance().getAllTipoDeUsuarios();
        List<Usuario> usuarios = FacadeInstance.getInstance().getAllUsuarios();
        
        int i, c;
        
        i = cbbTipoDeUsuario.getSelectedIndex();
        if(validaCampos() == true){
            
            usuario.setEmail(txtEmail.getText());
            usuario.setLogin(txtUsuario.getText());
            usuario.setSenha(txtSenha.getText());
            usuario.setNome(txtNome.getText());
            usuario.setTipodeusuario(tipodeusuario.get(i).getNome());
            
            for(c = 0; c < usuarios.size(); c++){
                if(usuario.getLogin().equals(usuarios.get(c).getLogin())){
                    JOptionPane.showMessageDialog(null, "Login existente!!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    return;
                }else if(usuario.getEmail().equals(usuarios.get(c).getEmail())){
                    JOptionPane.showMessageDialog(null, "Email ja existe!!", "Atenção", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            FacadeInstance.getInstance().saveUsuario(usuario);
            
            txtEmail.setText(null);
            txtUsuario.setText(null);
            txtSenha.setText(null);
            txtNome.setText(null);
            
            JOptionPane.showMessageDialog(null, "Usuario Adicionado", "Parabéns", JOptionPane.INFORMATION_MESSAGE);
            
            this.lista = FacadeInstance.getInstance().getAllUsuarios();
            this.listaTipo = FacadeInstance.getInstance().getAllTipoDeUsuarios();
            this.atualizarTabela(this.lista);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtEmail.setText("");
        txtNome.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");
        cbbTipoDeUsuario.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        this.selecionado = this.tblUsuario.getSelectedRow();
        
        if(this.selecionado != -1 && escolher == true){
            this.usuario = this.listaBuscar.get(this.selecionado);
        }else if(this.selecionado != -1){
            this.usuario = this.lista.get(this.selecionado);
        } 
        
        if (this.usuario != null) {
            txtNomeEdit.setText(this.usuario.getNome());
            txtEmailEdit.setText(this.usuario.getEmail());
            txtSenhaEdit.setText(this.usuario.getSenha());
            txtUsuarioEdit.setText(this.usuario.getLogin());
            
            int index = 0;
            
            for(index = 0; index < listaTipo.size(); index++){
                if(listaTipo.get(index).getNome().equals(this.usuario.getTipodeusuario())){
                    break;
                }
            }
            
            cbbTipoDeUsuarioEdit.setSelectedIndex(index);
            
            txtNomeEdit.setEnabled(true);
            
            btnCancelarEdit.setEnabled(true);
            btnExcluirEdit.setEnabled(true);
            btnSalvarEdit.setEnabled(true);
        } else {
            btnCancelarEdit.doClick();
        }
        escolher = false;
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void btnSalvarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditActionPerformed
        this.selecionado =  this.tblUsuario.getSelectedRow();
        
        if(this.selecionado != -1){
        
            int i;
        
            i = cbbTipoDeUsuarioEdit.getSelectedIndex();
        
            List<TipoDeUsuario> tiposdeusuarios = FacadeInstance.getInstance().getAllTipoDeUsuarios();
            
            if(validaCampos() == true){
        
                usuario.setEmail(txtEmailEdit.getText());
                usuario.setLogin(txtUsuarioEdit.getText());
                usuario.setSenha(txtSenhaEdit.getText());
                usuario.setNome(txtNomeEdit.getText());
                usuario.setTipodeusuario(tiposdeusuarios.get(i).getNome());
        
                FacadeInstance.getInstance().updateUsuario(usuario);
                
                txtEmailEdit.setText(null);
                txtUsuarioEdit.setText(null);
                txtSenhaEdit.setText(null);
                txtNomeEdit.setText(null);
        
                JOptionPane.showMessageDialog(null, "Usuario Atualizado", "Parabéns", JOptionPane.INFORMATION_MESSAGE);
        
                this.lista = FacadeInstance.getInstance().getAllUsuarios();
                this.listaTipo = FacadeInstance.getInstance().getAllTipoDeUsuarios();
                this.atualizarTabela(this.lista);
            }
            
        } else{
            JOptionPane.showMessageDialog(null, "Selecione corretamente um Usuario para ser atualizado!!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        btnCancelarEdit.doClick();
    }//GEN-LAST:event_btnSalvarEditActionPerformed

    private void btnExcluirEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEditActionPerformed
        FacadeInstance.getInstance().deleteUsuario(usuario);
        this.lista = FacadeInstance.getInstance().getAllUsuarios();
        this.listaTipo = FacadeInstance.getInstance().getAllTipoDeUsuarios();
        this.atualizarTabela(this.lista);
        
        this.selecionado = -1;
        
        JOptionPane.showMessageDialog(null, "Usuario Excluído", "Atenção", JOptionPane.WARNING_MESSAGE);
        
        btnCancelarEdit.doClick();
    }//GEN-LAST:event_btnExcluirEditActionPerformed

    private void btnCancelarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditActionPerformed
        txtEmailEdit.setText("");
        txtNomeEdit.setText("");
        txtUsuarioEdit.setText("");
        txtSenhaEdit.setText("");
        cbbTipoDeUsuarioEdit.setSelectedIndex(0);
        
        txtEmailEdit.setEnabled(false);
        txtNomeEdit.setEnabled(false);
        txtUsuarioEdit.setEnabled(false);
        txtSenhaEdit.setEnabled(false);
        cbbTipoDeUsuarioEdit.setEnabled(false);
        btnCancelarEdit.setEnabled(false);
        btnExcluirEdit.setEnabled(false);
        btnSalvarEdit.setEnabled(false);
    }//GEN-LAST:event_btnCancelarEditActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailEditKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailEditKeyPressed

    private void txtNomeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEditActionPerformed

    private void cbbTipoDeUsuarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTipoDeUsuarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTipoDeUsuarioEditActionPerformed

    private void btnHomescreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomescreenActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        homescreen retornar = new homescreen();
        retornar.setVisible(true);
    }//GEN-LAST:event_btnHomescreenActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        String nome = txtBuscaUsuario.getText();
        int i;
        List<Usuario> buscaUsuario = FacadeInstance.getInstance().getAllUsuarios();
        
        for(i = 0; i < buscaUsuario.size(); i++){
            if(nome.equals(buscaUsuario.get(i).getNome())){
                this.listaBuscar = FacadeInstance.getInstance().findByName(nome);
                this.atualizarTabela(listaBuscar);
                txtNomeEdit.setText(buscaUsuario.get(i).getNome());
                txtEmailEdit.setText(buscaUsuario.get(i).getEmail());
                txtSenhaEdit.setText(buscaUsuario.get(i).getSenha());
                txtUsuarioEdit.setText(buscaUsuario.get(i).getLogin());
                
                escolher = true;
            }
        }
        
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarUsuariosActionPerformed
        // TODO add your handling code here:
        this.lista = FacadeInstance.getInstance().getAllUsuarios();
        this.listaTipo = FacadeInstance.getInstance().getAllTipoDeUsuarios();
        this.atualizarTabela(this.lista);
        tblUsuario.setEnabled(true);
        
        this.selecionado = this.tblUsuario.getSelectedRow();
        
        if(this.selecionado != -1){
            this.usuario = this.listaBuscar.get(this.selecionado);
            escolher = false;
        }
    }//GEN-LAST:event_btnMostrarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarEdit;
    private javax.swing.JButton btnExcluirEdit;
    private javax.swing.JButton btnHomescreen;
    private javax.swing.JButton btnMostrarUsuarios;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarEdit;
    private javax.swing.JComboBox<String> cbbTipoDeUsuario;
    private javax.swing.JComboBox<String> cbbTipoDeUsuarioEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBuscaUsuario;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblDescricao3;
    private javax.swing.JLabel lblDescricao4;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JTable tblDescricao;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTabbedPane tbpDescricao;
    private javax.swing.JTextField txtBuscaUsuario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailEdit;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEdit;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaEdit;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioEdit;
    // End of variables declaration//GEN-END:variables
    private boolean validaCampos(){
        StringUtil util = StringUtil.getInstance();
        if (txtNome.getText().equals("") && txtEmail.getText().equals("") && txtSenha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios.", "CAMPOS OBRIGATÓRIOS", JOptionPane.ERROR_MESSAGE);
        return false;
        
        }
        else if(util.isNullOrEmpty(txtNome.getText())){
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome.", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
            
        }
        else if(util.isNullOrEmpty(txtEmail.getText())){
            JOptionPane.showMessageDialog(null, "Preencha o campo Email", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
            
        }
        else if(util.isNullOrEmpty(txtSenha.getText())){
            JOptionPane.showMessageDialog(null, "Preencha o campo Senha", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
       
        }
        else if (util.isNullOrEmpty(txtUsuario.getText())){
            JOptionPane.showMessageDialog(null, "Preencha o campo Usuario", "CAMPOS OBRIGATÓRIOS", JOptionPane.WARNING_MESSAGE);
            return false;
            
        }
        return true;
    }
}
