/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.salmos.login.forgotPassword;

import javax.swing.JOptionPane;

import br.com.ifba.salmos.infrastructure.service.FacadeInstance;
import br.com.ifba.salmos.usuario.model.Usuario;

/**
 *
 * @author tarciiz
 */
public class ChangePassword extends javax.swing.JFrame {
    Usuario user;

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword(Usuario user) {
        initComponents();
        this.user = user;
        this.txtEmail.setText(user.getEmail());
    }

    public ChangePassword() {
        initComponents();
    }

    public void salvar() {
        if (String.valueOf(txtNewPass.getPassword()).equals(String.valueOf(txtNewPassRepeat.getPassword()))) {
            // alterar
            this.user.setSenha(String.valueOf(txtNewPass.getPassword()));

            FacadeInstance.getInstance().updateUsuario(user);
            JOptionPane.showMessageDialog(null, "Sucesso, senha alterada com sucesso!",
                    "Sucesso!", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "As senhas devem ser iguais!",
                    "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewPass = new javax.swing.JPasswordField();
        txtNewPassRepeat = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblSenhaRepeat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPassKeyReleased(evt);
            }
        });

        txtNewPassRepeat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPassRepeatKeyReleased(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblSenha.setText("Nova Senha");

        lblSenhaRepeat.setText("Repita a senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSenhaRepeat)
                                        .addComponent(lblSenha)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnSalvar)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtNewPass, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                125, Short.MAX_VALUE)
                                                        .addComponent(txtNewPassRepeat)
                                                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addContainerGap(106, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(lblSenhaRepeat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewPassRepeat, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30,
                                        Short.MAX_VALUE)
                                .addComponent(btnSalvar)
                                .addGap(26, 26, 26)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalvarActionPerformed
        this.salvar();
    }// GEN-LAST:event_btnSalvarActionPerformed

    private void txtNewPassKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNewPassKeyReleased
        if (evt.getKeyCode() == (java.awt.event.KeyEvent.VK_ENTER)) {
            txtNewPassRepeat.requestFocus();
        }
    }// GEN-LAST:event_txtNewPassKeyReleased

    private void txtNewPassRepeatKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNewPassRepeatKeyReleased
        if (evt.getKeyCode() == (java.awt.event.KeyEvent.VK_ENTER)) {
            this.salvar();
        }
    }// GEN-LAST:event_txtNewPassRepeatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaRepeat;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtNewPassRepeat;
    // End of variables declaration//GEN-END:variables
}
