/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.salmos.login.forgotPassword;

import br.com.ifba.salmos.infrastructure.service.FacadeInstance;
import br.com.ifba.salmos.infrastructure.support.EmailUtil;
import br.com.ifba.salmos.usuario.model.Usuario;

import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author tarciiz
 */
public class ForgotPassword extends javax.swing.JFrame {
    String code;
    String email;
    Usuario user = null;
    boolean emailSent = false;

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        changeActive(emailSent);
    }

    private void changeActive(boolean isactive) {
        this.txtCode1.setEnabled(isactive);
        this.txtCode2.setEnabled(isactive);
        this.txtCode3.setEnabled(isactive);
        this.txtCode4.setEnabled(isactive);
        this.txtCode5.setEnabled(isactive);
        this.btnVerify.setEnabled(isactive);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCode1 = new javax.swing.JTextField();
        txtCode2 = new javax.swing.JTextField();
        txtCode3 = new javax.swing.JTextField();
        txtCode4 = new javax.swing.JTextField();
        txtCode5 = new javax.swing.JTextField();
        btnVerify = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtCode1.setBackground(new java.awt.Color(253, 255, 175));
        txtCode1.setBorder(null);
        txtCode1.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtCode1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCode1KeyReleased(evt);
            }
        });

        txtCode2.setBackground(new java.awt.Color(253, 255, 175));
        txtCode2.setBorder(null);
        txtCode2.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtCode2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCode2KeyReleased(evt);
            }
        });

        txtCode3.setBackground(new java.awt.Color(253, 255, 175));
        txtCode3.setBorder(null);
        txtCode3.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtCode3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCode3KeyReleased(evt);
            }
        });

        txtCode4.setBackground(new java.awt.Color(253, 255, 175));
        txtCode4.setBorder(null);
        txtCode4.setSelectionColor(new java.awt.Color(250, 206, 86));
        txtCode4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCode4KeyReleased(evt);
            }
        });

        txtCode5.setBackground(new java.awt.Color(253, 255, 175));
        txtCode5.setBorder(null);
        txtCode5.setSelectionColor(new java.awt.Color(250, 206, 86));

        btnVerify.setBackground(new java.awt.Color(250, 206, 86));
        btnVerify.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        btnVerify.setForeground(new java.awt.Color(253, 255, 175));
        btnVerify.setText("VERIFICAR");
        btnVerify.setBorder(null);
        btnVerify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(253, 255, 175));
        txtEmail.setBorder(null);
        txtEmail.setSelectionColor(new java.awt.Color(250, 206, 86));

        btnEnviar.setBackground(new java.awt.Color(250, 206, 86));
        btnEnviar.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(253, 255, 175));
        btnEnviar.setText("ENVIAR");
        btnEnviar.setBorder(null);
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCode5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEnviarActionPerformed
        if (!this.emailSent) {
            this.email = txtEmail.getText();
            for (Usuario user : (List<Usuario>) FacadeInstance.getInstance().getAllUsuarios()) {
                if (user.getEmail().equals(this.email)) {
                    this.user = user;
                    break;
                }
            }

            if (this.user == null) {
                JOptionPane.showMessageDialog(null, "O email informado não corresponde a nenhuma usuário cadastrado!",
                        "Erro!", JOptionPane.ERROR_MESSAGE);
            } else {

                this.code = "";
                for (int i = 0; i < 5; i++) {
                    this.code += String.valueOf(new Random().nextInt(10));
                }
                System.out.println("Code : " + this.code);

                this.emailSent = EmailUtil.sendRecoverPasswordEmail(email, this.code, this.user);

                changeActive(this.emailSent);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "O email já foi enviado!\nCaso não o veja na caixa de entrada, veifique sua caixa de span\nou tente mais tarde!",
                    "Já foi enviado!", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnEnviarActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVerifyActionPerformed
        String codeCheck = txtCode1.getText() +
                txtCode2.getText() +
                txtCode3.getText() +
                txtCode4.getText() +
                txtCode5.getText();
        System.out.println("Codigo informado: " + codeCheck);
        if (codeCheck.equals(this.code)) {
            ChangePassword cps = new ChangePassword(this.user);
            cps.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "O código informado está errado!", "Erro!", JOptionPane.ERROR_MESSAGE);

        }
    }// GEN-LAST:event_btnVerifyActionPerformed

    private void txtCode1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCode1KeyReleased
        txtCode2.requestFocus();
    }// GEN-LAST:event_txtCode1KeyReleased

    private void txtCode2KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCode2KeyReleased
        txtCode3.requestFocus();
    }// GEN-LAST:event_txtCode2KeyReleased

    private void txtCode3KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCode3KeyReleased
        txtCode4.requestFocus();
    }// GEN-LAST:event_txtCode3KeyReleased

    private void txtCode4KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCode4KeyReleased
        txtCode5.requestFocus();
    }// GEN-LAST:event_txtCode4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVerify;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCode1;
    private javax.swing.JTextField txtCode2;
    private javax.swing.JTextField txtCode3;
    private javax.swing.JTextField txtCode4;
    private javax.swing.JTextField txtCode5;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
