/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.ifba.salmos.requisicao.view;

import br.com.ifba.salmos.infrastructure.service.FacadeInstance;
import br.com.ifba.salmos.item.model.Item;
import br.com.ifba.salmos.requisicao.model.ItensDisponiveisTableModel;
import br.com.ifba.salmos.requisicao.model.Requisicao;
import br.com.ifba.salmos.setor.model.Setor;
import br.com.ifba.salmos.usuario.model.Usuario;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author rocki.julius
 */
public class ViewCadastroRequisicao extends javax.swing.JFrame {

    private Usuario usuarioLogado;
    private List<Setor> setores;
    private Collection<Item> itens;
    private Collection<Item> itensRequisitados = new ArrayList();
    ItensDisponiveisTableModel itensDisponiveis = new ItensDisponiveisTableModel();
    
    
    /** Creates new form ViewCadastroRequisicao */
        
    public ViewCadastroRequisicao(Usuario usuarioLogado) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioLogado = usuarioLogado;
        jLblUsuario.setText(this.usuarioLogado.getNome());
        iniciaComboBoxSetor();
        atualizaTabela();
        
    }
    
    public ViewCadastroRequisicao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnTelaRequisicoes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCmBoxSetor = new javax.swing.JComboBox<>();
        jLblUsuario = new javax.swing.JLabel();
        jBtnSalvarRequisicao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBtnAdicionaListaRequisicao = new javax.swing.JButton();
        jBtnRemoveListaRequisicao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerQuantidadeItemSelecionado = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableItensDisponiveis = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItensRequisitados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnTelaRequisicoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/salmos/image/voltar.png"))); // NOI18N
        jBtnTelaRequisicoes.setToolTipText("Voltar tela");
        jBtnTelaRequisicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTelaRequisicoesActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnTelaRequisicoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 441, -1, -1));

        jLabel1.setText("Setor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 67, -1, -1));

        jLabel2.setText("Usuário requisitante:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        getContentPane().add(jCmBoxSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 64, -1, -1));
        getContentPane().add(jLblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 32, 100, 21));

        jBtnSalvarRequisicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/salmos/image/salvar.png"))); // NOI18N
        jBtnSalvarRequisicao.setToolTipText("Salvar Requisição");
        jBtnSalvarRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarRequisicaoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalvarRequisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));

        jLabel3.setText("Itens disponíveis:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 102, -1, -1));

        jBtnAdicionaListaRequisicao.setText(">>>");
        jBtnAdicionaListaRequisicao.setToolTipText("Adicionar Item");
        jBtnAdicionaListaRequisicao.setEnabled(false);
        jBtnAdicionaListaRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionaListaRequisicaoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdicionaListaRequisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jBtnRemoveListaRequisicao.setText("<<<");
        jBtnRemoveListaRequisicao.setToolTipText("Remover Item");
        getContentPane().add(jBtnRemoveListaRequisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel4.setText("Quantidade:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));
        getContentPane().add(jSpinnerQuantidadeItemSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 55, -1));

        jTableItensDisponiveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableItensDisponiveis.setToolTipText("ItensDisponíveis");
        jTableItensDisponiveis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableItensDisponiveisFocusLost(evt);
            }
        });
        jTableItensDisponiveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensDisponiveisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableItensDisponiveis);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 185, 270));

        jListItensRequisitados.setToolTipText("Itens requisitados");
        jScrollPane1.setViewportView(jListItensRequisitados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 160, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTelaRequisicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTelaRequisicoesActionPerformed
        new ViewRequisicao(usuarioLogado).setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnTelaRequisicoesActionPerformed

    private void jBtnAdicionaListaRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionaListaRequisicaoActionPerformed
        int codItem = pegaCod();
        int qtdSolicitada = Integer.parseInt(jSpinnerQuantidadeItemSelecionado.getValue().toString());
        Item itemLocalizado = localizaItem(codItem);
        Item itemRequisitado = new Item();
                               
        if(verificaQuantidade(itemLocalizado, qtdSolicitada) == true){
            itemLocalizado.setQuantidade(itemLocalizado.getQuantidade() - qtdSolicitada);
            FacadeInstance.getInstance().updateItem(itemLocalizado);
            itemRequisitado = alteraInformacoesItem(itemLocalizado, qtdSolicitada);
            itensRequisitados.add(itemRequisitado);
            atualizaTabela();
            atualizaLista();
        }
    }//GEN-LAST:event_jBtnAdicionaListaRequisicaoActionPerformed

    private void jTableItensDisponiveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensDisponiveisMouseClicked
        jBtnAdicionaListaRequisicao.setEnabled(true);
    }//GEN-LAST:event_jTableItensDisponiveisMouseClicked

    private void jTableItensDisponiveisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableItensDisponiveisFocusLost

    }//GEN-LAST:event_jTableItensDisponiveisFocusLost

    private void jBtnSalvarRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarRequisicaoActionPerformed
        Requisicao req = new Requisicao();
        req.setListaItens(itens);
        req.setUsuario(usuarioLogado.getId());
        req.setSetor(jCmBoxSetor.getSelectedItem().toString());
        FacadeInstance.getInstance().saveRequisicao(req);
    }//GEN-LAST:event_jBtnSalvarRequisicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroRequisicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroRequisicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionaListaRequisicao;
    private javax.swing.JButton jBtnRemoveListaRequisicao;
    private javax.swing.JButton jBtnSalvarRequisicao;
    private javax.swing.JButton jBtnTelaRequisicoes;
    private javax.swing.JComboBox<String> jCmBoxSetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblUsuario;
    private javax.swing.JList<String> jListItensRequisitados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerQuantidadeItemSelecionado;
    private javax.swing.JTable jTableItensDisponiveis;
    // End of variables declaration//GEN-END:variables

    private boolean verificaQuantidade(Item itemLocalizado, int qtdSolicitada) {
        boolean qtd = false;
        int qntSolicitada = Integer.parseInt(jSpinnerQuantidadeItemSelecionado.getValue().toString());
        
        if(itemLocalizado.getQuantidade() < qntSolicitada){
            JOptionPane.showMessageDialog(null, "Quantidade solicitada maior que quantidade disponível!");
            qtd = false;
        }else{
            qtd = true;
        }
        return qtd;
    }
    
    private int pegaCod(){
        int linha = jTableItensDisponiveis.getSelectedRow();
        int cod = Integer.parseInt(itensDisponiveis.getValueAt(linha, 0).toString());
        return cod;
    }
    
    private void iniciaComboBoxSetor(){
        setores = FacadeInstance.getInstance().getAllSetor();
        for(int x = 0; x < setores.size(); x++){
            jCmBoxSetor.addItem(setores.get(x).getNome());
        }
    }
    
    private void atualizaTabela() {
        itensDisponiveis.atualizaListaRequisicao();
        jTableItensDisponiveis.setModel(itensDisponiveis);
    }

    private Item localizaItem(int cod) {
        Item itemALocalizar = new Item();
        itens = FacadeInstance.getInstance().getAllItem();
                
        for(Item itens: itens){
            if(itens.getId() == cod){
                itemALocalizar = itens;
                break;
            }
        }
              
        return itemALocalizar;
    }

    private void atualizaLista() {
        DefaultListModel model = new DefaultListModel();
        for(Item itensRequisitados: itensRequisitados){
            model.addElement("Item: " + itensRequisitados.getNome() + ". Quantidade: " + itensRequisitados.getQuantidade());
        }
        jListItensRequisitados.setModel(model);
    }

    private Item alteraInformacoesItem(Item itemLocalizado, int qtdSolicitada) {
        Item itemRequisitado = new Item();
        itemRequisitado.setId(itemLocalizado.getId());
        itemRequisitado.setDescricao(itemLocalizado.getDescricao());
        itemRequisitado.setNome(itemLocalizado.getNome());
        itemRequisitado.setQuantidade(qtdSolicitada);
        return itemRequisitado;
    }
}
